### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by pengrun** [passerbycrk/MacWeChatTimeLinePlugin#1]
cp: /Applications/WeChat.app/Contents/MacOS/WeChat_: Permission denied
cp: /Applications/WeChat.app/Contents/MacOS/MacWeChatTimeLinePlugin.framework: Permission denied
/Users/pengrun/Library/Developer/Xcode/DerivedData/MacWeChatTimeLinePlugin-esnxlnaeepcqqbbxwpgksmklhhka/Build/Intermediates/MacWeChatTimeLinePlugin.build/Debug/MacWeChatTimeLinePlugin.build/Script-DF5F532E1E7792310089EC7D.sh: line 20: ./insert_dylib: Permission denied

木有权限肿么破？

**Comment by luoerming** [comment]
一样啊怎么搞？？？

**Comment by pengrun** [comment]
我也没弄好。

**Comment by passerbycrk** [comment]
需要用chmod命令提权

**Comment by pengrun** [comment]
已经提到777了。还是不行哦。
